version: "3.9"

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  server:
    container_name: server
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/home/api
      - api_node_modules:/home/api/node_modules
volumes:
  postgres_data:
  api_node_modules:
